# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hiforge < Formula
  desc "HiForge CLI — local agent runtime and management tool for the HiForge platform"
  homepage "https://github.com/kaeljune/hiforge-cli"
  version "0.2.27"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kaeljune/hiforge-cli/releases/download/v0.2.27/hiforge-cli-0.2.27-darwin-amd64.tar.gz"
      sha256 "2b3ba934fd16bd73dcdb602418b2e8d2fc1c24d7a19c874dfadc5e7c954b0ac5"

      define_method(:install) do
        bin.install "hiforge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kaeljune/hiforge-cli/releases/download/v0.2.27/hiforge-cli-0.2.27-darwin-arm64.tar.gz"
      sha256 "0a3d689ba824bf47d2c74552879417ede29a683f25f7ccad744e8da74778f846"

      define_method(:install) do
        bin.install "hiforge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kaeljune/hiforge-cli/releases/download/v0.2.27/hiforge-cli-0.2.27-linux-amd64.tar.gz"
      sha256 "c7615ee4db18ac16a0a204a0947dbdff5827db6ccbb24a91f12003581753b664"
      define_method(:install) do
        bin.install "hiforge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kaeljune/hiforge-cli/releases/download/v0.2.27/hiforge-cli-0.2.27-linux-arm64.tar.gz"
      sha256 "bead643523e9766538ed47f1e776f90b1a290dd7df7423ea6cd6e5f5020848e0"
      define_method(:install) do
        bin.install "hiforge"
      end
    end
  end

  test do
    system "#{bin}/hiforge", "version"
  end
end
